name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Runs on pull requests to the 'main' branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (example for Node.js apps)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build  # Ensures this runs after the build job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test  # Ensures this runs after the test job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: |
          echo "Deploying application..."
          # Add your deployment commands here, such as:
          # scp files or deploy via a CI/CD tool like kubectl, AWS CLI, etc.
  
