name: Basic CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the application
        run: echo "Building the application..."  # Replace with your actual build commands

  test:
    runs-on: ubuntu-latest
    needs: build  # Run after the build stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: echo "Running tests..."  # Replace with your actual test commands

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Run after the test stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: echo "Deploying application..."  # Replace with your actual deployment commands
  
